name: Cargo build and test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Check Formatting
      run: cargo fmt --all -- --check
    - name: Check Clippy
      run: cargo clippy --all

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --verbose --all-features
      - name: Test
        run: cargo test --verbose

